- name: task1 - run apt update
  apt:
   update_cache: true
- name: Install apache
  apt:
   name: apache2
   state: present
- name: task1 - run apt update
  apt:
   update_cache: true
- name: task2 - Install mysql
  apt:
   name: "{{ mysql_package_name }}"
   state: "{{ mysql_package_state }}"
- name: copy configuration files
  copy:
   src: server.xml
   dest: /home/devops
